### ISSUE TITLE
FB id is been saved to the email field after loggedin

### ISSUE THREAD

**Issue by cayasso** [bnoguchi/mongoose-auth#11]
Here is what I get after a login, you will notice the code bellow from the collection output. 

<pre> "email": "fb: 100000647911219" </pre>

Also the email address shouldn't be saving any value since its optional when using facebook or other strategies, but required when using pasword or adding profile info after logged-in with facebook for instance.

This is the output after loggedin

<pre>
{
   "_id": ObjectId("4dc07411cbf9defd1a000008"),
   "fb": {
     "name": {
       "last": "Brumley",
       "first": "Jonathan",
       "full": "Jonathan Eushell Brumley" 
    },
     "updatedTime": "2011-05-02T03: 31: 20+0000",
     "verified": true,
     "locale": "en_US",
     "timezone": "-6",
     "gender": "male",
     "alias": "jobrumley",
     "expires": "Wed, 31 Dec 1969 18: 00: 05 -0600",
     "accessToken": "180675088648545|2.GpF7_O_6a9AcUVCwjgTwPQ__.3600.1304463600.1-100000647911219|pmoWGfQK8lC-4ADfrewOSAiYW-0",
     "id": "100000647911219" 
  },
   "email": "fb: 100000647911219" 
}
</pre>

Thank you Brian!
JB

**Comment by bnoguchi** [comment]
This is done intentionally, due to the way mongodb treats unique indexes. mongoose-auth sets up email as a unique index, so you avoid scenarios where the same email can sign up twice. So we are forced to deal with the way that mongodb treats unique indexes. MongoDB itself (not mongoose itself) handles unique indexes in the following way:

If you were to save a User document with no email, then mongodb automatically fills it in with `null`. Mongodb treats `null`s with the same unique index constraints, so if you try registering another user also e.g., via facebook, without saving an email, then mongodb will refuse to save it because you will just have tried to save a 2nd document that _also_ has the email value `null`.

I chose to fill in a default value for the email field of "#{module_name}:#{unique_id_with_provider}", because that is unique across all documents and will not violate uniqueness constraints.

**Comment by cayasso** [comment]
OK I got you, what about something like this as format <code>100000647911219@fb</code> so I can parse the field like this (in case i ever need to)

<pre>
var temp = "100000647911219@fb".split("@");
var tempId = temp[0];
var registeredFrom = temp[1];
</pre>


At the same time is invalid email but its verbose "xxxxx number at facebook". I am not saying this is important but it makes a bit more sence in case someone want to do something crazy like knowing how much users from facebook hasn't register an email address.

I am just saying :-)

JB

**Comment by bnoguchi** [comment]
In this case, it's better as the current colon delimited version. You can split on ":" if you need to. More importantly, because you lead with the source name instead of the provider uid, you can leverage mongodb's indexes for faster counting and lookup instead of doing the counting in the client or app.

**Comment by cayasso** [comment]
Great point about leverage mongodb's indexes, I was thinking more about the extra space after the colon but I can live with that. Thank you Brian for your quick replies.

**Comment by cayasso** [comment]
Ohh another thing just make sure you add all this great info to the README, for people to be aware and not bother you ;)

**Comment by bnoguchi** [comment]
The extra space after the colon is a typo in my code. Will patch that.

**Comment by cayasso** [comment]
Ahh ok nice! Thank you Brian.
Howdy from Costa Rica!

JB
