### ISSUE TITLE
password module: cannot override extractExtraRegistrationParams

### ISSUE THREAD

**Issue by troygoode** [bnoguchi/mongoose-auth#16]
## The Problem

The change to index.js in [commit e7108009316a51aa809e087f3307ceb8c7a8071b](https://github.com/bnoguchi/mongoose-auth/commit/e7108009316a51aa809e087f3307ceb8c7a8071b#index.js) - namely the addition of specialOptHandlers - means there is no clear way override the extractExtraRegistrationParams step. On the README you do it like so:

```
      , everyauth: {
            getLoginPath: '/login'
          , postLoginPath: '/login'
          , loginView: 'login.jade'
          , getRegisterPath: '/register'
          , postRegisterPath: '/register'
          , registerView: 'register.jade'
          , loginSuccessRedirect: '/'
          , registerSuccessRedirect: '/'

            // These are the NEW lines
          , extractExtraRegistrationParams: function (req) {
              return {
                  phone: req.body.phone
                , name: {
                      first: req.body.first_name
                  }
              };
            }
```

... but this doesn't actually work anymore, as the definition of extractExtraRegistrationParams is overwritten by the specialOpt recursion version.
## Why is this a problem?

Auto-recursion means you cannot whitelist/blacklist user input. If a user adds a field to a form before submitting (via FireBug or whatever) it will then automatically be mapped by the recursive implementation of extractExtraRegistrationParams and saved to the database.

**Comment by bnoguchi** [comment]
Oops. This is mis-documented (during a copy/paste from my everyauth library). You should not configure `extractExtraRegistrationParams` because the `extraParams` configuration does that for you automatically. I've updated the README with the correct instructions and explanation for adding extra parameters for the registration process.

On your perceived auto-recursion issue, I am going to have to dis-agree with you about the recursion disallowing white/blacklisting of input. The way the code is set up, the only parameters we ever pull from `req.body` is limited to the parameters that you want added to the registration form (and also auto-added to your schema) via `extraParams`. In other words, `extraParams` is a whitelist approach.

**Comment by troygoode** [comment]
Aha. What I hadn't realized was that I could still pass model definition stuff into the call to "new Schema({})", rather than having to force everything into the call to "UserSchema.plugin(...)".

**Comment by aadamowski** [comment]
But what if I want to use `extractExtraRegistrationParams` to actually extract some additional data from the actual req?

Like in this example for handling reCaptcha (which uses plain everyauth, not mongoose-auth):

https://github.com/JustinBeckwith/ExpressStarter/blob/master/server.js

``` javascript
.extractExtraRegistrationParams(function(req) {
        return {
            confirmPassword: req.body.confirmPassword,
            data: {
                remoteip: req.connection.remoteAddress,
                challenge: req.body.recaptcha_challenge_field,
                response: req.body.recaptcha_response_field
            }
        }
    })
```

**Comment by aadamowski** [comment]
For the record, I've ended up writing a parameterized function generation function.

It generates the function to be used for everyauth's `extractExtraRegistrationParams` and, if used, there must be no `extraParams` defined through mongoose-auth (otherwise it will sit unused).

``` javascript
function generateExtractionFunction(schemaAttrs) {
  return function(req) {

    // 1. Collect schema-mapper params like mongoose-auth/lib/modules/password/index.js does:
    function recurse (obj, ret, prefix) {
      ret || (ret = {});
      prefix || (prefix = []);
      return Object.keys(obj).reduce( function (ret, k) {
        prefix.push(k);
        if (obj[k].constructor == Object && !obj[k].type) {
          ret[k] = recurse(obj[k], {}, prefix);
        } else {
          ret[k] = req.body[prefix.join('.')];
        }
        prefix.pop(k);
        return ret;
      }, ret);
    }
    var params = recurse(schemaAttrs);

    // 2. Add recaptcha params extracted from req:
    params['recaptchaData'] = utilRecaptcha.extractRecaptchaDataFromReq(req);
    console.log('extraParams: [%j]', params);

    return params;
  }
}
```

As can be seen, the generated function performs both the logic of extraParams (extracting schema keys from request body) and reCaptcha request param extraction.

It pollutes the user attributes with reCaptcha data, so this data must be removed during the validation step immediatly after use.
Otherwise, it will be stored in the user account in MongoDB.

See below:

``` javascript
exports.validateRegistration = function (newUserAttributes, baseErrors) {
  var promise = this.Promise();

  var recaptcha = utilRecaptcha.createRecaptcha(newUserAttributes.recaptchaData);
  // Delete reCaptcha data so that it doesn't pollute user database:
  delete newUserAttributes.recaptchaData;
  console.log('newUserAttributes: [%j]', newUserAttributes);

  recaptcha.verify(function(success, error_code) {
    if(success) {
      console.log('Recaptcha PASSED, client IP: [%s]', recaptcha.data.remoteip);
      promise.fulfill(null);
    } else {
      console.log('Recaptcha error code [%s], client IP: [%s]', error_code, recaptcha.data.remoteip);
      baseErrors.push('reCaptcha error');
      promise.fulfill(baseErrors);
    }
  });
  return promise;
}

exports.userRegisterLocals = {
  recaptcha_form: utilRecaptcha.createRecaptcha().toHTML()
}

exports.everyauthRoutes = function(schemaAttrs){
  return {
    getLoginPath: '/login',
    postLoginPath: '/login',
    loginView: 'login/index.jade',
    getRegisterPath: '/reg/user',
    postRegisterPath: '/reg/user',
    registerView: 'reg/user/index.jade',
    loginSuccessRedirect: '/',
    registerSuccessRedirect: '/reg',
    registerLocals: exports.userRegisterLocals,
    extractExtraRegistrationParams: generateExtractionFunction(schemaAttrs),
    validateRegistration: exports.validateRegistration
  };
}
```

All this is packed in a separate module, which is used by the one that actually configures mongoose-auth (note the non-usage of `extraParams`):

``` javascript
  password: {
    //extraParams: schemaAttrs,
    everyauth: daorouteUser.everyauthRoutes(schemaAttrs)
  }
```
